# ML Term Paper - Code: Binary Models 
by Ann-Christin and Sarah 02/03/2021

## 1. Preparation

In [1]:
# import libraries
import os
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.svm import l1_min_c
from time import time
from sklearn import linear_model

from sklearn.model_selection import RepeatedKFold
from sklearn.linear_model import Lasso
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import KFold, cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegressionCV
from tabulate import tabulate

np.random.seed(100)
seed = 42

from sklearn import ensemble
from sklearn import tree as tree

# set color theme
sns.set_theme()

#specify your directories
# path = "E:\Data\krea\PIAAC" #enter your path here
path = "C:/Users/gust/Documents/ML_term_paper"
dir_lasso="results/models/" # where the outputs are saved 

#pd.set_option("display.max_rows", None, "display.max_columns", None)

In [2]:
os.chdir(path)
print("done")
data = pd.read_csv("data/piaac_red.csv", sep=',', error_bad_lines=False, index_col=False)
data.shape

done

C:\Users\gust\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (1,4,11,17,22,24,25,28,30,31,38,47,50,57,58,59,62,63,65,68,75,84,85,86,92) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

(230691, 129)

In [3]:
# data cleaning, drop variables that have too few observations,are not relevant or collinear
dcl = data.drop(columns = ['Unnamed: 0','inpiaac', "racethn_5cat", "unempflag", "racethn_5cat", "c_q08c2", "seqid", "b_q04b", "b_q19a", 
                         "c_q08c2", "learnatwork", "nfehrsnjr", "nfehrsjr", "nfehrs", "earnmthselfppp", "d_q05b2", 
                          "yrsqual_t", "earnmthbonusppp",  "d_q16d5", "c_q02c", "isco1c", "c_d09", "isic1l", "cnt_h", "isced_hf", "isco1l", "isco1c", "c_d05",
                          'icthome','ictwork','b_q01a','b_q01a_t','yrsqual','ageg10lfs','cnt_brth','fnfaet12jr', 'fe12', 'aetpop', 'faet12', 'faet12jr', 'faet12njr', 
                           'nfe12', 'nfe12jr', 'nfe12njr', 'fnfaet12', 'fnfaet12jr', 'fnfaet12njr']) # exlude those to test the results 
#"isic2l", "isic2c", "isic_cus_c", "isic_lus_c", "isic4_c", "isic4_l",

# further exclude 
dcl = dcl.drop(columns = ['d_q16b', 'b_q20b', 'b_d12h', 'b_q02a_t2', 'b_q11', 'b_q12e', 'd_q12a' , 'b_q04a', 'b_q16', 'b_q26b', 'b_q15c', 'd_q06c', 'b_q15b', 'd_q05a2', 
                          'b_q13', 'b_q15a', 'b_q16', 'b_q02a', 'b_q02a_t1', 'b_q05c', 'b_q10b', 'c_d06', 'd_q04', 'b_q12g', 'b_q12b', 'b_q12d'])

# logit exclude 
dcl = dcl.drop(columns = ['b_q14b', 'b_q26a_t', 'b_q14a'])


dcl = dcl.loc[:, ~dcl.columns.str.endswith('_c')]
#drop if skill level is missing 
#dcl = dcl[dcl.iscoskil4 != "A"]
#dcl = dcl[dcl.iscoskil4 != "N"]
#dcl = dcl[dcl.iscoskil4 != "U"]

In [4]:
#dcl['d_q05a2'] = dcl['d_q05a2'].astype('object')
dcl['gender_r'] = dcl['gender_r'].astype('category')
dcl["age_r"] = pd.to_numeric(dcl["age_r"])
dcl['b_q12a'] = dcl['b_q12a'].astype('category') # yes/no open educational training
#dcl['b_q12b'] = pd.to_numeric(dcl["b_q12b"]) # number of open/distance educational trainings
#dcl["b_q12d"] = pd.to_numeric(dcl["b_q12d"]) # number of on-the-job training
#dcl['b_q12e'] = dcl['b_q12e'].astype('category')  # yes/no seminars training
dcl['b_q12f'] = pd.to_numeric(dcl["b_q12f"]) # number of seminars
#dcl['b_q12g'] = dcl['b_q12g'].astype('category')  # yes/no private training
dcl['b_q12h'] = pd.to_numeric(dcl["b_q12h"]) # number of private educational trainings
# dcl['j_q03a'] = dcl['j_q03a'].astype('category') # yes/no children
dcl['j_q03b'] = pd.to_numeric(dcl['j_q03b']) # number of children
#dcl['yrsqual_t'] = pd.to_numeric(dcl['yrsqual_t'])
dcl['yrsget'] = pd.to_numeric(dcl['yrsget'])
dcl['iscoskil4'] = dcl['iscoskil4'].astype('category')
#dcl['h_q05g'] = dcl['h_q05g'].astype('category') # Skill use everyday life - ICT - Computer - How often - Programming language  
#dcl['g_q05g'] = dcl['g_q05g'].astype('category') # skill use work - ICT programming lanugage how often
#dcl['g_q05'] = dcl['g_q05'].astype('category') # use computer at work yes/no

In [5]:
cate = dcl.select_dtypes(include=['object', 'category'])
cate = cate.drop(columns = ["iscoskil4"]) 
cate = list(set(cate))
cate

['f_q07a',
 'f_q07b',
 'b_q12c',
 'g_q05g',
 'g_q07',
 'g_q05c',
 'g_q08',
 'vet',
 'g_q05e',
 'c_q02a',
 'gender_r',
 'g_q06',
 'd_q06a',
 'b_q01b',
 'j_q04a',
 'cntryid',
 'd_q06b',
 'edcat8',
 'g_q05h',
 'd_q13c',
 'd_q12b',
 'b_q10a',
 'pared',
 'd_q04_t',
 'd_q12c',
 'd_q09',
 'd_q03',
 'd_q14',
 'g_q05d',
 'g_q05f',
 'b_q12a',
 'd_q07a',
 'g_q05a',
 'computerexperience',
 'nopaidworkever',
 'isic1c',
 'b_q10c',
 'g_q04',
 'leaver1624']

In [6]:
# generate dummies                
dummies1 = [pd.get_dummies(dcl[i], prefix=i, drop_first = True) for i in [cate]]
dummies2 =  [pd.get_dummies(dcl["iscoskil4"], prefix="skill")] 
dummies1 = dummies1.pop(0)
dummies1

,f_q07a_Yes,f_q07b_Yes,b_q12c_Yes,g_q05g_Every day,g_q05g_Less than once a month,g_q05g_Less than once a week but at least once a month,g_q05g_Never,g_q07_Yes,g_q05c_Every day,g_q05c_Less than once a month,...,isic1c_Q,isic1c_R,isic1c_S,isic1c_T,isic1c_U,b_q10c_Not useful at all,b_q10c_Somewhat useful,b_q10c_Very useful,g_q04_Yes,"leaver1624_Not in education, did not complete ISCED 3, aged 16 to 24"
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1,1,0,0,0,1,0,1,0,...,1,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,1,0,0,0,1,1,1,0,...,0,0,1,0,0,0,0,0,1,0
4,1,0,0,0,0,0,1,1,1,0,...,0,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230686,1,1,0,0,0,0,1,1,1,0,...,0,1,0,0,0,0,0,0,1,0
230687,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
230688,1,1,1,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,1,0
230689,1,0,0,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,1,0
230690,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
# generate dummies                
dummies1 = [pd.get_dummies(dcl[i], prefix=i, drop_first = True) for i in [cate]]
dummies2 =  [pd.get_dummies(dcl["iscoskil4"], prefix="skill")] 
dummies1 = dummies1.pop(0)
dummies1 = pd.DataFrame(dummies1)
dummies2 = dummies2.pop(0)
dummies2 = pd.DataFrame(dummies2)
dummies = dummies1.join(dummies2)
dummies = dummies.drop(columns = ["skill_4","skill_U", "skill_A", "skill_N"])
dummies.head()
dummies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230691 entries, 0 to 230690
Columns: 173 entries, f_q07a_Yes to skill_3
dtypes: uint8(173)
memory usage: 38.1 MB

In [8]:
num = dcl.select_dtypes(include=['float64', "int32"])
num = num.loc[:, ~num.columns.str.startswith('b_q12')]

In [9]:
num.head()
num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230691 entries, 0 to 230690
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   age_r          166949 non-null  float64
 1   j_q03b         103091 non-null  float64
 2   yrsget         125736 non-null  float64
 3   c_q09          160575 non-null  float64
 4   c_q10a         147420 non-null  float64
 5   readytolearn   226734 non-null  float64
 6   earnmthallppp  88508 non-null   float64
dtypes: float64(7)
memory usage: 12.3 MB

In [10]:
num_list = list(set(num))
num_list

['c_q10a',
 'age_r',
 'c_q09',
 'yrsget',
 'j_q03b',
 'readytolearn',
 'earnmthallppp']

In [11]:
# define X and y
on_job = dummies["b_q12c_Yes"] #define y here
open_educ = dummies["b_q12a_Yes"]
X = num.join(dummies)
X = pd.DataFrame(np.ascontiguousarray(X.values), columns = X.columns)
X = X.drop(columns = ["b_q12c_Yes", "b_q12a_Yes"])
y = pd.DataFrame(dict(on_job=on_job, open_educ =open_educ))
y_X = y.join(X)
y_X

,on_job,open_educ,age_r,j_q03b,yrsget,c_q09,c_q10a,readytolearn,earnmthallppp,f_q07a_Yes,...,isic1c_T,isic1c_U,b_q10c_Not useful at all,b_q10c_Somewhat useful,b_q10c_Very useful,g_q04_Yes,"leaver1624_Not in education, did not complete ISCED 3, aged 16 to 24",skill_1,skill_2,skill_3
0,0,0,NaN,NaN,NaN,NaN,NaN,1.016017,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,1,NaN,NaN,19.0,NaN,NaN,2.164922,NaN,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2,0,0,NaN,NaN,NaN,NaN,NaN,1.177736,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,0,NaN,NaN,NaN,NaN,NaN,2.112932,NaN,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,0,1,NaN,NaN,NaN,NaN,NaN,3.064464,NaN,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230686,0,0,NaN,NaN,8.0,NaN,NaN,1.177736,NaN,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
230687,0,0,NaN,NaN,11.0,NaN,NaN,2.156445,NaN,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
230688,1,0,NaN,NaN,11.0,NaN,NaN,2.383062,NaN,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
230689,0,0,NaN,NaN,12.0,NaN,NaN,1.751830,NaN,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
230690,0,0,NaN,NaN,NaN,NaN,NaN,1.976309,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

## 2. Logit

### 2.1 Logit 'on_job'

In [12]:
import statsmodels.api as sm 

nona = y_X.drop(columns = ["open_educ","isic1c_9995", "isic1c_9996", "isic1c_9997", "isic1c_9998", "isic1c_9999"])
nona = nona.dropna()
nona = nona.loc[:, (nona != 0).any(axis=0)]
y = nona["on_job"]
X = nona.iloc[:, 1:]

In [13]:
X

,age_r,j_q03b,yrsget,c_q09,c_q10a,readytolearn,earnmthallppp,f_q07a_Yes,f_q07b_Yes,g_q05g_Every day,...,isic1c_T,isic1c_U,b_q10c_Not useful at all,b_q10c_Somewhat useful,b_q10c_Very useful,g_q04_Yes,"leaver1624_Not in education, did not complete ISCED 3, aged 16 to 24",skill_1,skill_2,skill_3
18418,33.0,2.0,11.0,6.0,1.0,2.361800,2500.0000,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
18423,43.0,1.0,11.0,24.0,1.0,1.124230,1343.1400,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
18433,53.0,2.0,9.0,27.0,2.0,0.788280,980.3900,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
18434,42.0,1.0,11.0,18.0,1.0,1.470600,1314.2200,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
18439,50.0,1.0,11.0,29.0,1.0,0.664940,1460.7800,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225548,43.0,2.0,15.0,23.0,1.0,1.239026,6153.8480,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
225552,42.0,2.0,12.0,22.0,1.0,1.177736,3509.6165,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
225554,24.0,1.0,12.0,6.0,15.0,2.004488,2500.0007,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
225555,51.0,3.0,8.0,35.0,2.0,1.002733,929.0080,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
225557,35.0,2.0,12.0,16.0,1.0,0.526827,2826.9240,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [14]:
logit_model=sm.Logit(y,X)
result = logit_model.fit()
print(result.summary2())

C:\Users\gust\Anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py:1747: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
C:\Users\gust\Anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py:1800: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))

Optimization terminated successfully.
         Current function value: inf
         Iterations 7

C:\Users\gust\Anaconda3\lib\site-packages\statsmodels\base\model.py:547: HessianInversionWarning: Inverting hessian failed, no bse or cov_params available
  warn('Inverting hessian failed, no bse or cov_params '
C:\Users\gust\Anaconda3\lib\site-packages\statsmodels\base\model.py:547: HessianInversionWarning: Inverting hessian failed, no bse or cov_params available
  warn('Inverting hessian failed, no bse or cov_params '

                                                       Results: Logit
=============================================================================================================================
Model:                                    Logit                                 Pseudo R-squared:                      inf
Dependent Variable:                       on_job                                AIC:                                   inf
Date:                                     2021-03-05 16:57                      BIC:                                   inf
No. Observations:                         40950                                 Log-Likelihood:                        -inf
Df Model:                                 151                                   LL-Null:                               0.0000
Df Residuals:                             40798                                 LLR p-value:                           1.0000
Converged:                                1.0000                                Scale:                                 1.0000
No. Iterations:                           7.0000
-----------------------------------------------------------------------------------------------------------------------------
                                                                              Coef.  Std.Err.    z     P>|z|   [0.025  0.975]
-----------------------------------------------------------------------------------------------------------------------------
age_r                                                                        -0.0194   0.0021  -9.1309 0.0000 -0.0236 -0.0152
j_q03b                                                                        0.0219   0.0115   1.9006 0.0574 -0.0007  0.0444
yrsget                                                                        0.0196   0.0059   3.3221 0.0009  0.0080  0.0312
c_q09                                                                         0.0121   0.0020   5.9470 0.0000  0.0081  0.0161
c_q10a                                                                       -0.0015   0.0073  -0.2033 0.8389 -0.0158  0.0128
readytolearn                                                                  0.0532   0.0130   4.1026 0.0000  0.0278  0.0787
earnmthallppp                                                                -0.0000   0.0000  -0.4890 0.6249 -0.0000  0.0000
f_q07a_Yes                                                                   -0.0413   0.0321  -1.2852 0.1987 -0.1042  0.0217
f_q07b_Yes                                                                    0.3316   0.0256  12.9432 0.0000  0.2814  0.3818
g_q05g_Every day                                                             -0.2193   0.1009  -2.1734 0.0298 -0.4170 -0.0215
g_q05g_Less than once a month                                                -0.0637   0.1014  -0.6282 0.5299 -0.2626  0.1351
g_q05g_Less than once a week but at least once a month                       -0.1158   0.1179  -0.9821 0.3260 -0.3470  0.1153
g_q05g_Never                                                                 -0.0405   0.0844  -0.4802 0.6311 -0.2059  0.1249
g_q07_Yes                                                                    -0.0445   0.0411  -1.0814 0.2795 -0.1251  0.0361
g_q05c_Every day                                                             -0.0037   0.0377  -0.0990 0.9212 -0.0776  0.0701
g_q05c_Less than once a month                                                -0.2054   0.0612  -3.3543 0.0008 -0.3254 -0.0854
g_q05c_Less than once a week but at least once a month                        0.0285   0.0577   0.4934 0.6218 -0.0846  0.1415
g_q05c_Never                                                                 -0.0515   0.0521  -0.9871 0.3236 -0.1536  0.0507
g_q08_Yes                                                                    -0.1162   0.0490  -2.3729 0.0177 -0.2122 -0.0202
vet_True                                                                      0.0745   0.0383   1.9471 0.0515 -0.0005  0.1495
g_q05e_Every day                                                             -0.0584   0.0421  -1.3870 0.1655 -0.1409  0.0241
g_q05e_Less than once a month                                                 0.0348   0.0550   0.6327 0.5270 -0.0730  0.1426
g_q05e_Less than once a week but at least once a month                        0.0154   0.0547   0.2816 0.7782 -0.0918  0.1226
g_q05e_Never                                                                 -0.0287   0.0499  -0.5749 0.5654 -0.1265  0.0691
gender_r_Male                                                                 0.0689   0.0283   2.4339 0.0149  0.0134  0.1245
g_q06_Moderate                                                                0.0176   0.0586   0.3011 0.7633 -0.0972  0.1325
g_q06_Straightforward                                                        -0.0042   0.0664  -0.0637 0.9492 -0.1345  0.1260
d_q06a_11 to 50 people                                                        0.3419   0.0328  10.4364 0.0000  0.2777  0.4062
d_q06a_251 to 1000 people                                                     0.6466   0.0432  14.9662 0.0000  0.5619  0.7312
d_q06a_51 to 250 people                                                       0.5493   0.0352  15.6000 0.0000  0.4803  0.6183
d_q06a_More than 1000 people                                                  0.6862   0.0496  13.8368 0.0000  0.5890  0.7834
b_q01b_Engineering, manufacturing and construction                            0.0467   0.0554   0.8426 0.3995 -0.0620  0.1554
b_q01b_General programmes                                                    -0.1263   0.0576  -2.1929 0.0283 -0.2391 -0.0134
b_q01b_Health and welfare                                                     0.2128   0.0669   3.1796 0.0015  0.0816  0.3439
b_q01b_Humanities, languages and arts                                        -0.0616   0.0681  -0.9043 0.3658 -0.1951  0.0719
b_q01b_Science, mathematics and computing                                     0.0447   0.0636   0.7024 0.4824 -0.0800  0.1695
b_q01b_Services                                                              -0.1696   0.0668  -2.5408 0.0111 -0.3004 -0.0388
b_q01b_Social sciences, business and law                                     -0.0059   0.0567  -0.1043 0.9169 -0.1170  0.1052
b_q01b_Teacher training and education science                                 0.2305   0.0674   3.4217 0.0006  0.0985  0.3626
j_q04a_Yes                                                                    0.0415   0.0423   0.9812 0.3265 -0.0414  0.1244
cntryid_218.0                                                                -0.5222   0.1163  -4.4916 0.0000 -0.7500 -0.2943
cntryid_300.0                                                                -1.9326   0.1554 -12.4377 0.0000 -2.2372 -1.6281
cntryid_376.0                                                                -0.6273   0.0942  -6.6561 0.0000 -0.8120 -0.4426
cntryid_398.0                                                                -1.7759   0.1044 -17.0189 0.0000 -1.9805 -1.5714
cntryid_440.0                                                                -0.8732   0.0918  -9.5073 0.0000 -1.0532 -0.6932
cntryid_484.0                                                                -0.4340   0.1009  -4.3012 0.0000 -0.6318 -0.2362
cntryid_152.0                                                                -0.2115   0.1335  -1.5846 0.1131 -0.4731  0.0501
cntryid_218.0                                                                -0.1351   0.1437  -0.9399 0.3473 -0.4168  0.1466
cntryid_300.0                                                                -1.7956   0.2014  -8.9159 0.0000 -2.1904 -1.4009
cntryid_376.0                                                                -0.6093   0.1302  -4.6815 0.0000 -0.8644 -0.3542
cntryid_398.0                                                                -1.8891   0.1437 -13.1414 0.0000 -2.1708 -1.6073
cntryid_440.0                                                                -0.6185   0.1173  -5.2718 0.0000 -0.8485 -0.3886
cntryid_484.0                                                                -0.3233   0.1319  -2.4505 0.0143 -0.5819 -0.0647
cntryid_705.0                                                                -0.7843   0.0854  -9.1805 0.0000 -0.9517 -0.6169
cntryid_Belgium                                                              -0.7362   0.0821  -8.9621 0.0000 -0.8972 -0.5752
cntryid_Czech Republic                                                        0.0562   0.0848   0.6632 0.5072 -0.1100  0.2225
cntryid_Denmark                                                              -0.4698   0.0771  -6.0896 0.0000 -0.6210 -0.3186
cntryid_France                                                               -1.2791   0.0787 -16.2616 0.0000 -1.4333 -1.1250
cntryid_Ireland                                                              -0.3463   0.0859  -4.0315 0.0001 -0.5146 -0.1779
cntryid_Italy                                                                -1.3722   0.1040 -13.1990 0.0000 -1.5760 -1.1684
cntryid_Japan                                                                -0.7269   0.0849  -8.5621 0.0000 -0.8933 -0.5605
cntryid_Korea                                                                -0.0300   0.0853  -0.3518 0.7250 -0.1972  0.1372
cntryid_Netherlands                                                          -0.0897   0.0829  -1.0830 0.2788 -0.2521  0.0727
cntryid_Norway                                                               -1.2253   0.0801 -15.2905 0.0000 -1.3823 -1.0682
cntryid_Poland                                                               -0.8824   0.0873 -10.1028 0.0000 -1.0536 -0.7112
cntryid_Russian Federation                                                   -1.7111   0.1110 -15.4101 0.0000 -1.9287 -1.4935
cntryid_Slovak Republic                                                      -0.8608   0.0848 -10.1487 0.0000 -1.0270 -0.6945
cntryid_Spain                                                                -0.2493   0.0855  -2.9153 0.0036 -0.4170 -0.0817
cntryid_United Kingdom                                                       -0.2298   0.0797  -2.8836 0.0039 -0.3860 -0.0736
d_q06b_Increased                                                              0.0313   0.0348   0.9009 0.3676 -0.0368  0.0995
d_q06b_Stayed more or less the same                                          -0.1657   0.0279  -5.9397 0.0000 -0.2203 -0.1110
edcat8_Post-secondary, non-tertiary (ISCED 4A-B-C)                            0.0124   0.0788   0.1568 0.8754 -0.1422  0.1669
edcat8_Primary or less (ISCED 1 or less)                                     -0.2026   0.0728  -2.7824 0.0054 -0.3453 -0.0599
edcat8_Tertiary - bachelor/master/research degree (ISCED 5A/6)               -0.0833   0.1020  -0.8166 0.4142 -0.2833  0.1167
edcat8_Tertiary – bachelor degree (ISCED 5A)                                  0.0619   0.0680   0.9103 0.3626 -0.0714  0.1953
edcat8_Tertiary – master degree (ISCED 5A)                                   -0.0270   0.0737  -0.3668 0.7138 -0.1716  0.1175
edcat8_Tertiary – professional degree (ISCED 5B)                              0.1209   0.0652   1.8551 0.0636 -0.0068  0.2487
edcat8_Tertiary – research degree (ISCED 6)                                  -0.6243   0.1259  -4.9579 0.0000 -0.8711 -0.3775
edcat8_Upper secondary (ISCED 3A-B, C long)                                   0.0302   0.0525   0.5747 0.5655 -0.0727  0.1330
g_q05h_Every day                                                             -0.0324   0.0811  -0.3989 0.6900 -0.1914  0.1267
g_q05h_Less than once a month                                                 0.0307   0.0723   0.4246 0.6712 -0.1110  0.1724
g_q05h_Less than once a week but at least once a month                        0.0120   0.0808   0.1481 0.8823 -0.1464  0.1703
g_q05h_Never                                                                 -0.2210   0.0620  -3.5618 0.0004 -0.3426 -0.0994
d_q13c_Every day                                                             -0.0210   0.0363  -0.5789 0.5626 -0.0921  0.0501
d_q13c_Less than once a month                                                -0.1947   0.0350  -5.5665 0.0000 -0.2632 -0.1261
d_q13c_Less than once a week but at least once a month                       -0.1090   0.0363  -3.0070 0.0026 -0.1801 -0.0380
d_q13c_Never                                                                 -0.5711   0.0469 -12.1803 0.0000 -0.6630 -0.4792
d_q12b_A lower level would be sufficient                                     -0.0491   0.0424  -1.1583 0.2467 -0.1323  0.0340
d_q12b_This level is necessary                                               -0.0278   0.0353  -0.7869 0.4313 -0.0971  0.0415
b_q10a_Yes                                                                    0.1330   0.0869   1.5296 0.1261 -0.0374  0.3034
pared_At least one parent has attained tertiary                              -0.0014   0.0327  -0.0443 0.9647 -0.0656  0.0627
pared_Neither parent has attained upper secondary                            -0.0379   0.0278  -1.3621 0.1732 -0.0924  0.0166
d_q04_t_Employee, supervising fewer than 5 people                             0.1014   0.0337   3.0067 0.0026  0.0353  0.1675
d_q04_t_Employee, supervising more than 5 people                              0.2663   0.0343   7.7707 0.0000  0.1992  0.3335
d_q12c_1 to 6 months                                                         -0.0865   0.0369  -2.3424 0.0192 -0.1589 -0.0141
d_q12c_3 years or more                                                       -0.0397   0.0337  -1.1793 0.2383 -0.1057  0.0263
d_q12c_7 to 11 months                                                        -0.0312   0.0499  -0.6254 0.5317 -0.1290  0.0666
d_q12c_Less than 1 month                                                     -0.2268   0.0566  -4.0083 0.0001 -0.3376 -0.1159
d_q12c_None                                                                  -0.0475   0.0349  -1.3600 0.1738 -0.1160  0.0210
d_q09_A temporary employment agency contract                                 -0.1052   0.0996  -1.0563 0.2908 -0.3003  0.0900
d_q09_An apprenticeship or other training scheme                              0.0789   0.1706   0.4626 0.6437 -0.2555  0.4134
d_q09_An indefinite contract                                                  0.0854   0.0372   2.2961 0.0217  0.0125  0.1584
d_q09_No contract                                                            -0.5668   0.0680  -8.3368 0.0000 -0.7000 -0.4335
d_q09_Other                                                                   0.0332   0.1095   0.3030 0.7619 -0.1815  0.2479
d_q03_The private sector (for example a company)                             -0.3763   0.0701  -5.3664 0.0000 -0.5137 -0.2389
d_q03_The public sector (for example the local government or a state school) -0.1163   0.0714  -1.6297 0.1032 -0.2562  0.0236
d_q14_Extremely dissatisfied                                                 -0.0283   0.1238  -0.2289 0.8189 -0.2710  0.2143
d_q14_Extremely satisfied                                                     0.1416   0.0607   2.3315 0.0197  0.0226  0.2606
d_q14_Neither satisfied nor dissatisfied                                     -0.0330   0.0627  -0.5266 0.5985 -0.1560  0.0899
d_q14_Satisfied                                                               0.1020   0.0574   1.7752 0.0759 -0.0106  0.2146
g_q05d_Every day                                                             -0.0441   0.0593  -0.7437 0.4571 -0.1604  0.0722
g_q05d_Less than once a month                                                 0.0419   0.0648   0.6460 0.5183 -0.0852  0.1690
g_q05d_Less than once a week but at least once a month                        0.0017   0.0690   0.0243 0.9806 -0.1336  0.1370
g_q05d_Never                                                                  0.1303   0.0492   2.6485 0.0081  0.0339  0.2267
g_q05f_Every day                                                              0.1187   0.0387   3.0667 0.0022  0.0428  0.1946
g_q05f_Less than once a month                                                -0.0596   0.0630  -0.9456 0.3444 -0.1830  0.0639
g_q05f_Less than once a week but at least once a month                       -0.0115   0.0566  -0.2034 0.8388 -0.1224  0.0993
g_q05f_Never                                                                 -0.0258   0.0549  -0.4704 0.6380 -0.1334  0.0818
g_q05a_Every day                                                              0.0764   0.0511   1.4949 0.1349 -0.0238  0.1766
g_q05a_Less than once a month                                                -0.0850   0.0863  -0.9847 0.3247 -0.2540  0.0841
g_q05a_Less than once a week but at least once a month                        0.0538   0.0845   0.6365 0.5244 -0.1118  0.2194
g_q05a_Never                                                                 -0.1359   0.0630  -2.1564 0.0311 -0.2594 -0.0124
computerexperience_Yes                                                        0.0579   0.0525   1.1014 0.2707 -0.0451  0.1608
isic1c_A                                                                     -0.5239   0.1288  -4.0689 0.0000 -0.7763 -0.2715
isic1c_B                                                                     -0.0961   0.1607  -0.5978 0.5500 -0.4110  0.2189
isic1c_C                                                                     -0.5526   0.0993  -5.5656 0.0000 -0.7473 -0.3580
isic1c_D                                                                     -0.1591   0.1495  -1.0643 0.2872 -0.4520  0.1339
isic1c_E                                                                     -0.1964   0.1594  -1.2327 0.2177 -0.5088  0.1159
isic1c_F                                                                     -0.6724   0.1072  -6.2720 0.0000 -0.8825 -0.4623
isic1c_G                                                                     -0.4862   0.0999  -4.8663 0.0000 -0.6820 -0.2904
isic1c_H                                                                     -0.1779   0.1052  -1.6904 0.0910 -0.3841  0.0284
isic1c_I                                                                     -0.8211   0.1185  -6.9264 0.0000 -1.0534 -0.5887
isic1c_J                                                                     -0.4875   0.1165  -4.1837 0.0000 -0.7158 -0.2591
isic1c_K                                                                      0.0206   0.1140   0.1803 0.8569 -0.2028  0.2439
isic1c_L                                                                     -0.4602   0.1624  -2.8337 0.0046 -0.7785 -0.1419
isic1c_M                                                                     -0.6004   0.1116  -5.3806 0.0000 -0.8191 -0.3817
isic1c_N                                                                     -0.2566   0.1112  -2.3062 0.0211 -0.4746 -0.0385
isic1c_O                                                                     -0.2277   0.1030  -2.2103 0.0271 -0.4297 -0.0258
isic1c_P                                                                     -0.1845   0.1039  -1.7756 0.0758 -0.3881  0.0192
isic1c_Q                                                                     -0.0118   0.1010  -0.1169 0.9069 -0.2097  0.1861
isic1c_R                                                                     -0.3300   0.1334  -2.4736 0.0134 -0.5915 -0.0685
isic1c_S                                                                     -0.3942   0.1256  -3.1391 0.0017 -0.6404 -0.1481
isic1c_T                                                                     -1.4200   0.2440  -5.8193 0.0000 -1.8982 -0.9417
isic1c_U                                                                      0.1052   0.5798   0.1815 0.8560 -1.0311  1.2416
b_q10c_Not useful at all                                                     -0.3539   0.1415  -2.5019 0.0124 -0.6311 -0.0767
b_q10c_Somewhat useful                                                       -0.0872   0.1552  -0.5616 0.5744 -0.3913  0.2170

## 2.2 Logit 'off job'

In [15]:
import statsmodels.api as sm 

nona = y_X.drop(columns = ["on_job","isic1c_9995", "isic1c_9996", "isic1c_9997", "isic1c_9998", "isic1c_9999"])
nona = nona.dropna()
nona = nona.loc[:, (nona != 0).any(axis=0)]
y = nona["open_educ"]
X = nona.iloc[:, 1:]

In [16]:
logit_model=sm.Logit(y,X)
result = logit_model.fit()
print(result.summary2())

C:\Users\gust\Anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py:1747: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
C:\Users\gust\Anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py:1800: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))

Optimization terminated successfully.
         Current function value: inf
         Iterations 8

C:\Users\gust\Anaconda3\lib\site-packages\statsmodels\base\model.py:547: HessianInversionWarning: Inverting hessian failed, no bse or cov_params available
  warn('Inverting hessian failed, no bse or cov_params '
C:\Users\gust\Anaconda3\lib\site-packages\statsmodels\base\model.py:547: HessianInversionWarning: Inverting hessian failed, no bse or cov_params available
  warn('Inverting hessian failed, no bse or cov_params '

                                                       Results: Logit
=============================================================================================================================
Model:                                    Logit                                 Pseudo R-squared:                      inf
Dependent Variable:                       open_educ                             AIC:                                   inf
Date:                                     2021-03-05 16:57                      BIC:                                   inf
No. Observations:                         40950                                 Log-Likelihood:                        -inf
Df Model:                                 151                                   LL-Null:                               0.0000
Df Residuals:                             40798                                 LLR p-value:                           1.0000
Converged:                                1.0000                                Scale:                                 1.0000
No. Iterations:                           8.0000
-----------------------------------------------------------------------------------------------------------------------------
                                                                              Coef.  Std.Err.    z     P>|z|   [0.025  0.975]
-----------------------------------------------------------------------------------------------------------------------------
age_r                                                                        -0.0257   0.0034  -7.5503 0.0000 -0.0324 -0.0190
j_q03b                                                                        0.0010   0.0188   0.0535 0.9574 -0.0358  0.0378
yrsget                                                                        0.0114   0.0093   1.2283 0.2193 -0.0068  0.0297
c_q09                                                                         0.0201   0.0033   6.0659 0.0000  0.0136  0.0265
c_q10a                                                                       -0.0080   0.0118  -0.6764 0.4988 -0.0312  0.0152
readytolearn                                                                  0.0476   0.0192   2.4870 0.0129  0.0101  0.0852
earnmthallppp                                                                -0.0000   0.0000  -0.0877 0.9301 -0.0000  0.0000
f_q07a_Yes                                                                    0.0291   0.0512   0.5692 0.5692 -0.0712  0.1294
f_q07b_Yes                                                                    0.2526   0.0380   6.6417 0.0000  0.1780  0.3271
g_q05g_Every day                                                             -0.1083   0.1318  -0.8219 0.4111 -0.3667  0.1500
g_q05g_Less than once a month                                                -0.0182   0.1336  -0.1359 0.8919 -0.2800  0.2437
g_q05g_Less than once a week but at least once a month                        0.0584   0.1520   0.3845 0.7006 -0.2395  0.3563
g_q05g_Never                                                                 -0.0780   0.1111  -0.7016 0.4829 -0.2957  0.1398
g_q07_Yes                                                                     0.1548   0.0632   2.4506 0.0143  0.0310  0.2786
g_q05c_Every day                                                              0.0756   0.0541   1.3980 0.1621 -0.0304  0.1816
g_q05c_Less than once a month                                                -0.1922   0.1005  -1.9129 0.0558 -0.3891  0.0047
g_q05c_Less than once a week but at least once a month                       -0.1074   0.0901  -1.1909 0.2337 -0.2840  0.0693
g_q05c_Never                                                                 -0.2624   0.0877  -2.9920 0.0028 -0.4343 -0.0905
g_q08_Yes                                                                    -0.1739   0.0742  -2.3433 0.0191 -0.3193 -0.0284
vet_True                                                                     -0.0089   0.0659  -0.1347 0.8928 -0.1380  0.1203
g_q05e_Every day                                                              0.1239   0.0593   2.0889 0.0367  0.0077  0.2402
g_q05e_Less than once a month                                                -0.0139   0.0787  -0.1761 0.8602 -0.1680  0.1403
g_q05e_Less than once a week but at least once a month                        0.1085   0.0759   1.4294 0.1529 -0.0403  0.2573
g_q05e_Never                                                                  0.0993   0.0728   1.3646 0.1724 -0.0433  0.2419
gender_r_Male                                                                -0.1021   0.0424  -2.4096 0.0160 -0.1851 -0.0190
g_q06_Moderate                                                                0.0012   0.0784   0.0147 0.9883 -0.1525  0.1548
g_q06_Straightforward                                                        -0.0666   0.0917  -0.7259 0.4679 -0.2463  0.1132
d_q06a_11 to 50 people                                                        0.0341   0.0529   0.6456 0.5185 -0.0695  0.1377
d_q06a_251 to 1000 people                                                     0.2049   0.0672   3.0489 0.0023  0.0732  0.3365
d_q06a_51 to 250 people                                                       0.1603   0.0557   2.8764 0.0040  0.0511  0.2694
d_q06a_More than 1000 people                                                  0.2744   0.0730   3.7575 0.0002  0.1313  0.4175
b_q01b_Engineering, manufacturing and construction                           -0.0680   0.0936  -0.7264 0.4676 -0.2514  0.1155
b_q01b_General programmes                                                    -0.2821   0.1009  -2.7970 0.0052 -0.4798 -0.0844
b_q01b_Health and welfare                                                     0.2002   0.1056   1.8961 0.0579 -0.0067  0.4071
b_q01b_Humanities, languages and arts                                        -0.0114   0.1058  -0.1079 0.9141 -0.2187  0.1959
b_q01b_Science, mathematics and computing                                     0.0244   0.1003   0.2438 0.8074 -0.1721  0.2210
b_q01b_Services                                                              -0.1618   0.1162  -1.3922 0.1639 -0.3896  0.0660
b_q01b_Social sciences, business and law                                     -0.0788   0.0925  -0.8522 0.3941 -0.2600  0.1024
b_q01b_Teacher training and education science                                 0.1478   0.1030   1.4345 0.1514 -0.0541  0.3498
j_q04a_Yes                                                                   -0.2732   0.0648  -4.2133 0.0000 -0.4003 -0.1461
cntryid_218.0                                                                -0.4019   0.1636  -2.4572 0.0140 -0.7225 -0.0813
cntryid_300.0                                                                -1.9170   0.2908  -6.5914 0.0000 -2.4871 -1.3470
cntryid_376.0                                                                -1.0651   0.1367  -7.7899 0.0000 -1.3330 -0.7971
cntryid_398.0                                                                -0.6764   0.1326  -5.1027 0.0000 -0.9362 -0.4166
cntryid_440.0                                                                 0.2551   0.1178   2.1654 0.0304  0.0242  0.4860
cntryid_484.0                                                                -0.5225   0.1445  -3.6171 0.0003 -0.8056 -0.2394
cntryid_152.0                                                                 0.0098   0.1676   0.0584 0.9534 -0.3188  0.3383
cntryid_218.0                                                                -0.1188   0.1874  -0.6342 0.5260 -0.4862  0.2485
cntryid_300.0                                                                -0.8555   0.2710  -3.1564 0.0016 -1.3867 -0.3243
cntryid_376.0                                                                -0.8568   0.1819  -4.7103 0.0000 -1.2133 -0.5003
cntryid_398.0                                                                -1.1607   0.2053  -5.6537 0.0000 -1.5630 -0.7583
cntryid_440.0                                                                 0.3609   0.1475   2.4470 0.0144  0.0718  0.6500
cntryid_484.0                                                                -0.3124   0.1930  -1.6192 0.1054 -0.6906  0.0658
cntryid_705.0                                                                -1.6491   0.1480 -11.1431 0.0000 -1.9392 -1.3590
cntryid_Belgium                                                              -1.5184   0.1354 -11.2121 0.0000 -1.7838 -1.2529
cntryid_Czech Republic                                                       -1.2931   0.1392  -9.2875 0.0000 -1.5660 -1.0202
cntryid_Denmark                                                              -0.6215   0.1046  -5.9403 0.0000 -0.8265 -0.4164
cntryid_France                                                               -2.1475   0.1489 -14.4196 0.0000 -2.4394 -1.8556
cntryid_Ireland                                                              -1.6027   0.1388 -11.5501 0.0000 -1.8747 -1.3307
cntryid_Italy                                                                -0.7249   0.1473  -4.9197 0.0000 -1.0137 -0.4361
cntryid_Japan                                                                -0.8608   0.1298  -6.6297 0.0000 -1.1153 -0.6063
cntryid_Korea                                                                 0.7909   0.1085   7.2922 0.0000  0.5783  1.0035
cntryid_Netherlands                                                          -0.4212   0.1106  -3.8085 0.0001 -0.6379 -0.2044
cntryid_Norway                                                               -1.8860   0.1262 -14.9412 0.0000 -2.1334 -1.6386
cntryid_Poland                                                                0.1993   0.1113   1.7897 0.0735 -0.0190  0.4175
cntryid_Russian Federation                                                   -0.7647   0.1443  -5.3007 0.0000 -1.0474 -0.4819
cntryid_Slovak Republic                                                      -1.5857   0.1515 -10.4640 0.0000 -1.8827 -1.2887
cntryid_Spain                                                                 0.0841   0.1119   0.7514 0.4524 -0.1352  0.3034
cntryid_United Kingdom                                                       -1.2218   0.1243  -9.8314 0.0000 -1.4654 -0.9782
d_q06b_Increased                                                              0.0249   0.0522   0.4762 0.6339 -0.0775  0.1272
d_q06b_Stayed more or less the same                                          -0.0562   0.0428  -1.3125 0.1894 -0.1401  0.0277
edcat8_Post-secondary, non-tertiary (ISCED 4A-B-C)                            0.1338   0.1323   1.0109 0.3121 -0.1256  0.3931
edcat8_Primary or less (ISCED 1 or less)                                     -0.4414   0.1508  -2.9268 0.0034 -0.7370 -0.1458
edcat8_Tertiary - bachelor/master/research degree (ISCED 5A/6)                0.1118   0.1660   0.6737 0.5005 -0.2136  0.4372
edcat8_Tertiary – bachelor degree (ISCED 5A)                                  0.3006   0.1130   2.6612 0.0078  0.0792  0.5220
edcat8_Tertiary – master degree (ISCED 5A)                                    0.3088   0.1205   2.5631 0.0104  0.0727  0.5449
edcat8_Tertiary – professional degree (ISCED 5B)                              0.1283   0.1111   1.1552 0.2480 -0.0894  0.3460
edcat8_Tertiary – research degree (ISCED 6)                                   0.0105   0.1828   0.0574 0.9542 -0.3477  0.3687
edcat8_Upper secondary (ISCED 3A-B, C long)                                   0.0510   0.0977   0.5215 0.6020 -0.1406  0.2425
g_q05h_Every day                                                              0.0826   0.0970   0.8512 0.3946 -0.1076  0.2727
g_q05h_Less than once a month                                                -0.0259   0.0895  -0.2892 0.7724 -0.2013  0.1495
g_q05h_Less than once a week but at least once a month                       -0.0438   0.0998  -0.4385 0.6610 -0.2393  0.1518
g_q05h_Never                                                                 -0.4101   0.0780  -5.2565 0.0000 -0.5630 -0.2572
d_q13c_Every day                                                             -0.0271   0.0527  -0.5136 0.6076 -0.1303  0.0762
d_q13c_Less than once a month                                                -0.1202   0.0529  -2.2727 0.0230 -0.2238 -0.0165
d_q13c_Less than once a week but at least once a month                       -0.1316   0.0536  -2.4541 0.0141 -0.2367 -0.0265
d_q13c_Never                                                                 -0.4087   0.0777  -5.2631 0.0000 -0.5609 -0.2565
d_q12b_A lower level would be sufficient                                     -0.1366   0.0657  -2.0812 0.0374 -0.2653 -0.0080
d_q12b_This level is necessary                                               -0.2351   0.0531  -4.4299 0.0000 -0.3391 -0.1311
b_q10a_Yes                                                                    0.7681   0.1011   7.5954 0.0000  0.5699  0.9662
pared_At least one parent has attained tertiary                              -0.1002   0.0468  -2.1384 0.0325 -0.1920 -0.0084
pared_Neither parent has attained upper secondary                            -0.1075   0.0438  -2.4559 0.0141 -0.1932 -0.0217
d_q04_t_Employee, supervising fewer than 5 people                             0.0663   0.0512   1.2937 0.1958 -0.0341  0.1667
d_q04_t_Employee, supervising more than 5 people                              0.1331   0.0488   2.7304 0.0063  0.0376  0.2287
d_q12c_1 to 6 months                                                         -0.0775   0.0573  -1.3529 0.1761 -0.1898  0.0348
d_q12c_3 years or more                                                        0.0198   0.0493   0.4026 0.6873 -0.0768  0.1165
d_q12c_7 to 11 months                                                        -0.0721   0.0776  -0.9291 0.3528 -0.2243  0.0800
d_q12c_Less than 1 month                                                     -0.2525   0.0955  -2.6445 0.0082 -0.4397 -0.0654
d_q12c_None                                                                  -0.0365   0.0540  -0.6761 0.4990 -0.1424  0.0694
d_q09_A temporary employment agency contract                                  0.1118   0.1587   0.7042 0.4813 -0.1993  0.4228
d_q09_An apprenticeship or other training scheme                             -0.1329   0.2384  -0.5576 0.5771 -0.6002  0.3343
d_q09_An indefinite contract                                                 -0.0182   0.0551  -0.3302 0.7412 -0.1263  0.0898
d_q09_No contract                                                            -0.3262   0.1033  -3.1581 0.0016 -0.5287 -0.1238
d_q09_Other                                                                   0.1851   0.1484   1.2477 0.2122 -0.1057  0.4760
d_q03_The private sector (for example a company)                             -0.5441   0.0965  -5.6361 0.0000 -0.7333 -0.3549
d_q03_The public sector (for example the local government or a state school) -0.3468   0.0968  -3.5815 0.0003 -0.5367 -0.1570
d_q14_Extremely dissatisfied                                                 -0.4943   0.2137  -2.3133 0.0207 -0.9131 -0.0755
d_q14_Extremely satisfied                                                    -0.1305   0.0902  -1.4461 0.1481 -0.3073  0.0464
d_q14_Neither satisfied nor dissatisfied                                     -0.2123   0.0936  -2.2672 0.0234 -0.3959 -0.0288
d_q14_Satisfied                                                              -0.2334   0.0853  -2.7359 0.0062 -0.4006 -0.0662
g_q05d_Every day                                                              0.0648   0.0802   0.8080 0.4191 -0.0924  0.2219
g_q05d_Less than once a month                                                -0.0650   0.0890  -0.7303 0.4652 -0.2394  0.1094
g_q05d_Less than once a week but at least once a month                        0.0860   0.0915   0.9398 0.3473 -0.0934  0.2654
g_q05d_Never                                                                  0.0149   0.0680   0.2189 0.8267 -0.1183  0.1481
g_q05f_Every day                                                              0.0564   0.0550   1.0262 0.3048 -0.0513  0.1642
g_q05f_Less than once a month                                                -0.0325   0.0992  -0.3274 0.7434 -0.2269  0.1619
g_q05f_Less than once a week but at least once a month                       -0.1308   0.0867  -1.5090 0.1313 -0.3006  0.0391
g_q05f_Never                                                                 -0.0310   0.0859  -0.3610 0.7181 -0.1994  0.1374
g_q05a_Every day                                                              0.0534   0.0750   0.7117 0.4766 -0.0936  0.2003
g_q05a_Less than once a month                                                 0.0697   0.1324   0.5269 0.5983 -0.1897  0.3292
g_q05a_Less than once a week but at least once a month                        0.0934   0.1249   0.7472 0.4549 -0.1515  0.3382
g_q05a_Never                                                                  0.0092   0.0997   0.0919 0.9268 -0.1862  0.2045
computerexperience_Yes                                                        0.1932   0.1021   1.8923 0.0584 -0.0069  0.3934
isic1c_A                                                                     -1.2584   0.2242  -5.6138 0.0000 -1.6977 -0.8190
isic1c_B                                                                     -0.6660   0.2451  -2.7175 0.0066 -1.1463 -0.1856
isic1c_C                                                                     -1.0024   0.1479  -6.7767 0.0000 -1.2923 -0.7125
isic1c_D                                                                     -0.5164   0.2134  -2.4197 0.0155 -0.9347 -0.0981
isic1c_E                                                                     -0.5103   0.2486  -2.0529 0.0401 -0.9975 -0.0231
isic1c_F                                                                     -1.0389   0.1655  -6.2786 0.0000 -1.3632 -0.7146
isic1c_G                                                                     -0.8210   0.1482  -5.5403 0.0000 -1.1114 -0.5305
isic1c_H                                                                     -0.7636   0.1609  -4.7456 0.0000 -1.0790 -0.4482
isic1c_I                                                                     -1.0154   0.1843  -5.5106 0.0000 -1.3765 -0.6542
isic1c_J                                                                     -0.7503   0.1676  -4.4765 0.0000 -1.0788 -0.4218
isic1c_K                                                                     -0.2548   0.1593  -1.5995 0.1097 -0.5670  0.0574
isic1c_L                                                                     -0.7693   0.2407  -3.1965 0.0014 -1.2409 -0.2976
isic1c_M                                                                     -0.9281   0.1644  -5.6466 0.0000 -1.2502 -0.6059
isic1c_N                                                                     -0.7669   0.1696  -4.5212 0.0000 -1.0994 -0.4345
isic1c_O                                                                     -0.6614   0.1491  -4.4351 0.0000 -0.9536 -0.3691
isic1c_P                                                                     -0.4511   0.1494  -3.0205 0.0025 -0.7439 -0.1584
isic1c_Q                                                                     -0.6701   0.1486  -4.5094 0.0000 -0.9613 -0.3788
isic1c_R                                                                     -0.6298   0.1941  -3.2441 0.0012 -1.0102 -0.2493
isic1c_S                                                                     -1.0699   0.1955  -5.4726 0.0000 -1.4531 -0.6867
isic1c_T                                                                     -1.1234   0.3089  -3.6368 0.0003 -1.7288 -0.5180
isic1c_U                                                                     -0.2581   0.7370  -0.3502 0.7262 -1.7026  1.1865
b_q10c_Not useful at all                                                      0.0086   0.1680   0.0513 0.9591 -0.3208  0.3380
b_q10c_Somewhat useful                                                        0.2346   0.1762   1.3313 0.1831 -0.1108  0.5801

## 3. Logit with Penalty

## 3.1. 'on job training'

In [17]:
nona = y_X.drop(columns = ["open_educ","isic1c_9995", "isic1c_9996", "isic1c_9997", "isic1c_9998", "isic1c_9999"])
nona = nona.dropna()
nona = nona.loc[:, (nona != 0).any(axis=0)]
y = nona["on_job"]
X = nona.iloc[:, 1:]



# Split the data into test and training sets, with 30% of samples being put into the test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state= seed)

In [18]:
# Create a scaler object
sc = StandardScaler()

# Fit the scaler to the training data and transform
X_train_std = sc.fit_transform(X_train)

# Apply the scaler to the test data
X_test_std = sc.transform(X_test)

In [22]:
# logistic regression with lasso penalty and 5 fold cross validation
kf = KFold(n_splits=5, shuffle=False)
model=LogisticRegressionCV(Cs=20,cv=kf,penalty='l1',solver='liblinear',refit=True, random_state = seed).fit(X_train,y_train)

In [23]:
coef=model.coef_
len(coef[0]) 
np.savetxt(dir_lasso+"coef_lasso_logit_onjob.txt",coef[0])

In [24]:
# which value of c was selected (penalty)
C = float(model.C_)
print(C)

1.623776739188721

In [ ]:
# regularization path

cs = l1_min_c(X, y, loss='log') * np.logspace(0, 7, 16)


print("Computing regularization path ...")
start = time()
clf = linear_model.LogisticRegression(penalty='l1', solver='liblinear',
                                      tol=1e-6, max_iter=int(1e6),
                                      warm_start=True,
                                      intercept_scaling=10000.)
coefs_ = []
for c in cs:
    clf.set_params(C=c)
    clf.fit(X, y)
    coefs_.append(clf.coef_.ravel().copy())
print("This took %0.3fs" % (time() - start))

coefs_ = np.array(coefs_)
plt.plot(np.log10(cs), coefs_)
ymin, ymax = plt.ylim()
plt.xlabel('log(C)')
plt.ylabel('Coefficients')
#plt.title('Logistic Regression Path')
plt.axis('tight')
plt.savefig('results\plots\lasso_logit_on_job.png', bbox_inches='tight')
plt.show()

In [25]:
# rerun the regression with optmal penalty 
clf = LogisticRegression(penalty='l1', C=C, solver='liblinear', random_state=seed)
logit = clf.fit(X_train, y_train)

print(np.count_nonzero(clf.coef_)) 

y_pred=logit.predict(X_test)

from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

146

array([[5764, 1596],
       [2179, 2746]], dtype=int64)

In [ ]:
class_names=[0,1] # name  of classes
fig, ax = plt.subplots()
tick_marks = np.arange(len(class_names))
plt.xticks(tick_marks, class_names)
plt.yticks(tick_marks, class_names)
# create heatmap
sns.heatmap(pd.DataFrame(cnf_matrix), annot=True, cmap="YlGnBu" ,fmt='g')
ax.xaxis.set_label_position("top")
plt.tight_layout()
#plt.title('Confusion matrix', y=1.1)
plt.ylabel('Actual label')
plt.xlabel('Predicted label')
plt.savefig('results\plots\confusion_on_job.png', bbox_inches='tight')

In [26]:
print('Coefficient of each feature:', clf.coef_)
#print('Features:', list(X_train.columns))
print('Training accuracy:', logit.score(X_train_std, y_train))
print('Test accuracy:', clf.score(X_test_std, y_test))
print('')

Coefficient of each feature: [[-1.55907300e-02  3.02295664e-02  2.32019293e-02  9.90347711e-03
   3.37111751e-03  5.60054311e-02 -1.24821628e-07 -7.95609375e-03
   3.48551947e-01 -1.61546337e-01 -2.04278476e-02 -1.23127046e-01
   0.00000000e+00 -4.11870272e-03 -1.12438667e-02 -1.83506419e-01
   3.52710932e-02  0.00000000e+00 -1.35597245e-01  1.02230636e-01
  -2.37855436e-02  5.07559663e-02 -2.11324092e-03  0.00000000e+00
   5.77012263e-02 -3.68199334e-03 -7.36763463e-02  3.29073617e-01
   6.32761905e-01  5.53863950e-01  6.31392698e-01  5.75456525e-02
  -1.38605016e-01  2.30177511e-01 -8.07605534e-02  6.48152863e-03
  -1.24290549e-01  0.00000000e+00  2.09819130e-01  9.65918630e-02
  -3.58076484e-01 -1.75609142e+00 -5.05998658e-01 -1.67280035e+00
  -7.28547541e-01 -2.44652613e-01  7.03340309e-03 -1.07986963e-01
  -1.63855748e+00 -3.81929471e-01 -1.77843927e+00 -5.11587570e-01
  -1.05233937e-01 -6.12904068e-01 -5.88752350e-01  1.41281508e-01
  -3.82496349e-01 -1.14406691e+00 -2.12435184e-01 -1.25770319e+00
  -5.23911983e-01  1.73394696e-01  7.32221821e-02 -1.10371018e+00
  -7.37147821e-01 -1.56132462e+00 -6.77127832e-01 -7.49468043e-02
  -1.06726605e-01  1.44598480e-02 -1.69892709e-01  2.49435191e-02
  -2.00984670e-01 -2.24826183e-02  1.03158918e-01  5.68457036e-02
   1.65260352e-01 -6.13868109e-01  6.09672926e-02  2.18530528e-02
   1.20927413e-01  6.36719685e-02 -2.10578516e-01 -4.30228730e-02
  -1.96056613e-01 -1.48904066e-01 -5.99394131e-01 -2.32784733e-02
  -1.96135190e-02  1.62838241e-01 -1.62409233e-02 -1.61447477e-02
   1.32087337e-01  2.62529258e-01 -2.57581963e-02 -5.59076433e-02
  -1.78572652e-02 -1.70801993e-01 -3.19211467e-02 -1.23066431e-01
   3.04200535e-01  1.28429950e-01 -5.41264052e-01 -4.07293519e-02
  -2.13210046e-01  6.66069915e-02  0.00000000e+00  1.55907932e-01
  -3.90424307e-02  9.09277582e-02 -5.01058190e-02  4.02549144e-02
   4.55178743e-02  1.12039814e-01  1.13413318e-01 -6.02900152e-02
   3.81144509e-02  3.05648199e-02  1.16312167e-01 -4.06773730e-02
   1.21014894e-01 -1.66163848e-01  1.16777579e-01 -2.66594437e-01
   1.68277081e-01 -2.83319340e-01  2.01834631e-01  5.92602169e-02
  -3.88532674e-01 -2.03583293e-01  3.73620339e-02 -5.71334256e-01
  -1.94094220e-01  2.79579126e-01 -1.05811808e-01 -3.30413599e-01
   3.45861713e-02 -8.83753362e-03  1.08566567e-01  2.51649136e-01
   2.14235595e-03 -1.40317116e-02 -1.03559729e+00  4.87687159e-01
  -2.71501147e-01 -5.70796407e-03  0.00000000e+00  5.95028385e-01
  -1.85860655e-01  1.46937146e-01  5.32836456e-02  2.56809283e-01]]
Training accuracy: 0.6752485609628467
Test accuracy: 0.6662596662596663

In [ ]:
imp = pd.DataFrame(clf.coef_, index = ["Coefficients"]).T
imp['Feature'] = list(X_train.columns)
imp

In [ ]:
index = imp[(imp['Coefficients'] == 0)].index
imp.drop(index, inplace=True)
imp= imp[~imp['Feature'].astype(str).str.startswith('isic1c')]
imp= imp[~imp['Feature'].astype(str).str.startswith('cntryid')]
imp.reset_index(drop=True, inplace=True)
imp

In [ ]:
headers = ["Coefficients", "Feature"]
print(tabulate(imp, headers, tablefmt="pipe"))

In [ ]:
imp.sort_values("Coefficients").head(30)

In [ ]:
imp.sort_values("Coefficients", ascending = False).head(30)

In [ ]:
y_pred_proba = logit.predict_proba(X_test)[::,1]
fpr, tpr, _ = metrics.roc_curve(y_test,  y_pred_proba)
auc = metrics.roc_auc_score(y_test, y_pred_proba)
plt.plot(fpr,tpr,label="data 1, auc="+str(auc))
plt.legend(loc=4)
plt.savefig('results\plots\ROC_on_job.png', bbox_inches='tight')
plt.show()

### 3.2 open education

In [ ]:
nona = y_X.drop(columns = ["on_job","isic1c_9995", "isic1c_9996", "isic1c_9997", "isic1c_9998", "isic1c_9999"])
nona = nona.dropna()
nona = nona.loc[:, (nona != 0).any(axis=0)]
y = nona["open_educ"]
X = nona.iloc[:, 1:]

# Split the data into test and training sets, with 30% of samples being put into the test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state= seed)

In [ ]:
# Create a scaler object
sc = StandardScaler()

# Fit the scaler to the training data and transform
X_train_std = sc.fit_transform(X_train)

# Apply the scaler to the test data
X_test_std = sc.transform(X_test)

In [ ]:
# logistic regression with lasso penalty and 5 fold cross validation
model=LogisticRegressionCV(Cs=20,cv=5,penalty='l1',solver='liblinear',refit=True,  random_state = seed).fit(X_train,y_train)

In [ ]:
coef=model.coef_
len(coef[0]) 
np.savetxt(dir_lasso+"coef_lasso_logit_open.txt",coef[0])

In [ ]:
# which value of c was selected (penalty)
C = float(model.C_)
print(C)

In [ ]:
# regularization path (takes a lot of time)

cs = l1_min_c(X, y, loss='log') * np.logspace(0, 7, 16)


print("Computing regularization path ...")
start = time()
clf = linear_model.LogisticRegression(penalty='l1', solver='liblinear',
                                      tol=1e-6, max_iter=int(1e6),
                                      warm_start=True,
                                      intercept_scaling=10000.)
coefs_ = []
for c in cs:
    clf.set_params(C=c)
    clf.fit(X, y)
    coefs_.append(clf.coef_.ravel().copy())
print("This took %0.3fs" % (time() - start))

coefs_ = np.array(coefs_)
plt.plot(np.log10(cs), coefs_)
ymin, ymax = plt.ylim()
plt.xlabel('log(C)')
plt.ylabel('Coefficients')
#plt.title('Logistic Regression Path')
plt.axis('tight')
plt.savefig('results\plots\lasso_logit_open_educ.png', bbox_inches='tight')
plt.show()

In [ ]:
clf = LogisticRegression(penalty='l1', C=C, solver='liblinear', random_state=seed)
logit = clf.fit(X_train, y_train)

print(np.count_nonzero(clf.coef_)) 

y_pred=logit.predict(X_test)

from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

In [ ]:
class_names=[0,1] # name  of classes
fig, ax = plt.subplots()
tick_marks = np.arange(len(class_names))
plt.xticks(tick_marks, class_names)
plt.yticks(tick_marks, class_names)
# create heatmap
sns.heatmap(pd.DataFrame(cnf_matrix), annot=True, cmap="YlGnBu" ,fmt='g')
ax.xaxis.set_label_position("top")
plt.tight_layout()
#plt.title('Confusion matrix', y=1.1)
plt.ylabel('Actual label')
plt.xlabel('Predicted label')
plt.savefig('results\plots\confusion_open_educ.png', bbox_inches='tight')

In [ ]:
imp = pd.DataFrame(logit.coef_, index = ["Coefficients"]).T
imp['Feature'] = list(X_train.columns)
imp

In [ ]:
index = imp[(imp['Coefficients'] == 0)].index
imp.drop(index, inplace=True)
imp= imp[~imp['Feature'].astype(str).str.startswith('isic1c')]
imp= imp[~imp['Feature'].astype(str).str.startswith('cntryid')]
imp.reset_index(drop=True, inplace=True)
imp

In [ ]:
headers = ["Coefficients", "Feature"]
print(tabulate(imp, headers, tablefmt="pipe"))

In [ ]:
imp.sort_values("Coefficients").head(30)

In [ ]:
imp.sort_values("Coefficients", ascending = False).head(30)

In [ ]:
y_pred_proba = logit.predict_proba(X_test)[::,1]
fpr, tpr, _ = metrics.roc_curve(y_test,  y_pred_proba)
auc = metrics.roc_auc_score(y_test, y_pred_proba)
plt.plot(fpr,tpr,label="data 1, auc="+str(auc))
plt.legend(loc=4)
plt.savefig('results\plots\ROC_open_educ.png', bbox_inches='tight')
plt.show()

# predicted probability for a training participation

ypred_train=model.predict_proba(X_train)[:,1] 
ypred_test=model.predict_proba(X_test)[:,1]


np.savetxt(dir_lasso+"ypred_train_logit_open.txt",ypred_train)
np.savetxt(dir_lasso+"ypred_test_logit_open.txt",ypred_test)

In [ ]:
# out of sample result with lasso 
print('Training accuracy:', logit.score(X_train_std, y_train))
print('Test accuracy:', logit.score(X_test_std, y_test))
print('In-sample Rsq: % .4f'
     % logit.score(X_train, y_train))
print('Out-of-sample Rsq: % .4f'
     % logit.score(X_test, y_test))

### compare to logit without lasso 'on-job'

In [ ]:
# compare to logit without lasso 

nona = y_X.drop(columns = ["open_educ","isic1c_9995", "isic1c_9996", "isic1c_9997", "isic1c_9998", "isic1c_9999"])
nona = nona.dropna()
nona = nona.loc[:, (nona != 0).any(axis=0)]
y = nona["on_job"]
X = nona.iloc[:, 1:]

# Split the data into test and training sets, with 30% of samples being put into the test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state= seed)


regr =LogisticRegression(penalty='none', random_state=seed)
regr.fit(X_train, y_train)



# to see the coefficients
print('Intercept: %.3f' %regr.intercept_)
print('Coefficients: ' )
print(regr.coef_ )

y_pred_in = regr.predict(X_train)
y_pred_out = regr.predict(X_test)
print('Training accuracy:', regr.score(X_train_std, y_train))
print('Test accuracy:', regr.score(X_test_std, y_test))
# In-sample R-sq.
print('In-sample Rsq: %.3f'
      % r2_score(y_train, y_pred_in))
print('Out-of-sample Rsq: %.3f'
      % r2_score(y_test, y_pred_out))

In [ ]:
cnf_matrix = metrics.confusion_matrix(y_test, y_pred_out)
cnf_matrix

class_names=[0,1] # name  of classes
fig, ax = plt.subplots()
tick_marks = np.arange(len(class_names))
plt.xticks(tick_marks, class_names)
plt.yticks(tick_marks, class_names)
# create heatmap
sns.heatmap(pd.DataFrame(cnf_matrix), annot=True, cmap="YlGnBu" ,fmt='g')
ax.xaxis.set_label_position("top")
plt.tight_layout()
#plt.title('Confusion matrix', y=1.1)
plt.ylabel('Actual label')
plt.xlabel('Predicted label')
plt.savefig('results\plots\logit_confusion_open_educ.png', bbox_inches='tight')

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_out))

### compare to logit without lasso 'open educ'

In [ ]:
# compare to logit without lasso 

nona = y_X.drop(columns = ["on_job","isic1c_9995", "isic1c_9996", "isic1c_9997", "isic1c_9998", "isic1c_9999"])
nona = nona.dropna()
nona = nona.loc[:, (nona != 0).any(axis=0)]
y = nona["open_educ"]
X = nona.iloc[:, 1:]

# Split the data into test and training sets, with 30% of samples being put into the test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state= seed)


regr =LogisticRegression(penalty='none', random_state=seed)
regr.fit(X_train, y_train)



# to see the coefficients
print('Intercept: %.3f' %regr.intercept_)
print('Coefficients: ' )
print(regr.coef_ )

y_pred_in = regr.predict(X_train)
y_pred_out = regr.predict(X_test)
print('Training accuracy:', regr.score(X_train_std, y_train))
print('Test accuracy:', regr.score(X_test_std, y_test))
# In-sample R-sq.
print('In-sample Rsq: %.3f'
      % r2_score(y_train, y_pred_in))
print('Out-of-sample Rsq: %.3f'
      % r2_score(y_test, y_pred_out))

In [ ]:
cnf_matrix = metrics.confusion_matrix(y_test, y_pred_out)
cnf_matrix

class_names=[0,1] # name  of classes
fig, ax = plt.subplots()
tick_marks = np.arange(len(class_names))
plt.xticks(tick_marks, class_names)
plt.yticks(tick_marks, class_names)
# create heatmap
sns.heatmap(pd.DataFrame(cnf_matrix), annot=True, cmap="YlGnBu" ,fmt='g')
ax.xaxis.set_label_position("top")
plt.tight_layout()
#plt.title('Confusion matrix', y=1.1)
plt.ylabel('Actual label')
plt.xlabel('Predicted label')
plt.savefig('results\plots\logit_confusion_open_educ.png', bbox_inches='tight')

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_out))

In [ ]:
y_test.describe()